INSERT INTO public.learning_trails (
    id, course_code, title, axis, 
    credits_aula, credits_trabalho, prerequisites, 
    course_map, excitation_level, requires_pcc_validation
) VALUES 
(gen_random_uuid(), '4300231', 'Introdução à Epistemologia das Ciências', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'ACA0115', 'Introdução às Ciências Atmosféricas', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'AGA0100', 'Astronomia de Posição', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'MAC0110', 'Introdução à Computação para Ciências Exatas e Tecnologia', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300218', 'Introdução à Física Computacional', 'lic', 4, 2, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300350', 'Processos Criativos em Ciências: da Imaginação à Divulgação Científica', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'EDF0285', 'Introdução aos Estudos da Educação: Enfoque Filosófico', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'EDF0287', 'Introdução aos Estudos da Educação: Enfoque Histórico', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'EDF0289', 'Introdução aos Estudos da Educação: Enfoque Sociológico', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'MAE0116', 'Noções de Estatística', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'MAT0122', 'Álgebra Linear I', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '0440620', 'Geologia Geral', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300234', 'Física no Ensino Fundamental', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300318', 'Introdução à Física Computacional II', 'lic', 4, 2, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'AGA0215', 'Fundamentos de Astronomia', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'EDF0290', 'Teorias do Desenvolvimento, Práticas Escolares e Processos de Subjetivação', 'lic', 4, 1, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'EDF0292', 'Psicologia Histórico-Cultural e Educação', 'lic', 4, 1, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'EDF0296', 'Psicologia da Educação: Constituição do Sujeito, Desenvolvimento e Aprendizagem na Escola, Cultura e Sociedade', 'lic', 4, 1, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'EDF0298', 'Psicologia da Educação I: Uma Abordagem Psicossocial do Cotidiano Escolar', 'lic', 4, 1, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'EDF0299', 'Psicologia da Educação: Desenvolvimento e Práticas Escolares', 'lic', 4, 1, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300325', 'Métodos da Física Teórica', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300366', 'Partículas - a Dança da Matéria e dos Campos', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'AGA0210', 'Experimentos de Astronomia', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'AGA0315', 'Planetas e Sistemas Planetários', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'EDA0468', 'Educação especial, inclusão escolar e políticas de atendimento a alunos com deficiência...', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'EDM0400', 'Currículo e Avaliação', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300360', 'Física do Meio Ambiente', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'QFL0605', 'Química Geral', 'lic', 6, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300438', 'Efeitos Biológicos das Radiações Ionizantes e Não Ionizantes', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300491', 'Introdução à Pesquisa em Ensino de Física', 'lic', 2, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4302204', 'Física Matemática I', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4302260', 'Aceleradores de Partículas: Fundamentos e Aplicações', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4302305', 'Mecânica I / Mecânica Estatística', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'AGA0309', 'Mecânica Celeste', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300308', 'Termodinâmica', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300329', 'Física do Corpo Humano', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300346', 'Física da Poluição do Ar', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300375', 'Detectores de Radiação', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300456', 'Produção de Material Didático', 'lic', 4, 2, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300459', 'Tecnologias da Informação e Comunicação no Ensino de Física', 'lic', 2, 2, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300461', 'Tecnologia de Ensino de Física I', 'lic', 2, 2, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300490', 'Monografia para Licenciatura em Física', 'lic', 0, 4, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4302303', 'Eletromagnetismo I', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'FLF0487', 'Tópicos de Filosofia da Física', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'MAP0214', 'Cálculo Numérico com Aplicações em Física', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4302220', 'Introdução ao Caos', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300353', 'Tópicos de História da Física Clássica', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300370', 'Introdução à Física Nuclear e de Partículas Elementares', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300379', 'Introdução à Física do Estado Sólido', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300410', 'Ciência e Cultura', 'lic', 2, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300439', 'Laboratório de Dosimetria das Radiações / Cosmologia', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300462', 'Tecnologia de Ensino de Física II', 'lic', 2, 2, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300463', 'Física Aplicada', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4302313', 'Física Experimental IV / V', 'lic', 4, 2, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4302401', 'Eletromagnetismo I', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4302403', 'Mecânica Quântica I', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'AGA0316', 'Astrofísica de Altas Energias', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'AGA0414', 'Introdução à Cosmologia', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'FLF0472', 'Filosofia da Física', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), 'MAT0349', 'História da Matemática I', 'lic', 4, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300405', 'Evolução dos Conceitos da Física', 'lic', 2, 0, '{}', '{"licenciatura": "eletiva"}', null, false),
(gen_random_uuid(), '4300454', 'Tópicos de História da Física Moderna', 'lic', 2, 0, '{}', '{"licenciatura": "eletiva"}', null, false)
ON CONFLICT (course_code) DO UPDATE SET
    course_map = learning_trails.course_map || EXCLUDED.course_map,
    title = EXCLUDED.title,
    credits_aula = EXCLUDED.credits_aula,
    credits_trabalho = EXCLUDED.credits_trabalho;
