INSERT INTO public.learning_trails (
    id, course_code, title, axis, 
    credits_aula, credits_trabalho, prerequisites, 
    course_map, excitation_level, requires_pcc_validation
) VALUES 
(gen_random_uuid(), '4302111', 'Física I', 'med', 4, 0, '{}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4302113', 'Física Experimental I', 'med', 4, 0, '{}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MAT0112', 'Vetores e Geometria', 'med', 4, 0, '{}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MAT2453', 'Cálculo Diferencial e Integral I', 'med', 6, 0, '{}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4300208', 'Introdução à Termodinâmica', 'med', 2, 0, '{"4302111"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4302112', 'Física II', 'med', 4, 0, '{"4302111"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4302114', 'Física Experimental II', 'med', 4, 0, '{"4302113", "MAT2453"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MAT2454', 'Cálculo Diferencial e Integral II', 'med', 4, 0, '{"MAT2453"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0632', 'Introdução à Física Médica', 'med', 2, 0, '{}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0633', 'Elementos de Anatomia e Fisiologia Humana', 'med', 4, 0, '{}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4302211', 'Física III', 'med', 4, 0, '{"MAT0112", "MAT2454", "4302111"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4302213', 'Física Experimental III', 'med', 4, 2, '{"4302114", "MAT2454"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MAT0216', 'Cálculo Diferencial e Integral III / IV', 'med', 6, 0, '{"MAT2454"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0635', 'Estatística Médica I', 'med', 4, 0, '{}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4300218', 'Introdução à Física Computacional', 'med', 4, 2, '{"4302111"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4302212', 'Física IV', 'med', 4, 0, '{"4302112", "4302211"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4302214', 'Física Experimental IV', 'med', 4, 2, '{"4302213"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0634', 'Informática Médica e Saúde Digital', 'med', 4, 0, '{}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4300325', 'Física do Corpo Humano', 'med', 4, 0, '{"MAT2454", "4302112"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4302204', 'Física Matemática I', 'med', 4, 0, '{"MAT2454", "MAT0112"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MAT0122', 'Álgebra Linear I', 'med', 4, 0, '{}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0637', 'Diagnóstico por Imagens Médicas', 'med', 4, 0, '{"4302211", "4302112"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0639', 'Física do Diagnóstico por imagens I', 'med', 4, 0, '{"4302211", "MDR0633"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4300438', 'Efeitos Biológicos das Radiações Ionizantes e Não Ionizantes', 'med', 4, 0, '{}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4302305', 'Mecânica I', 'med', 4, 0, '{"MAT2454", "4302112"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4302311', 'Física Quântica', 'med', 2, 0, '{"MAT0216"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0636', 'Equipamentos Médico-Hospitalares I', 'med', 4, 0, '{"MDR0633"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4300437', 'Física das Radiações I', 'med', 6, 0, '{"4302311", "4302212"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4302303', 'Eletromagnetismo I', 'med', 4, 0, '{"MAT0216", "4302212"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4302403', 'Mecânica Quântica I', 'med', 4, 0, '{"4302204", "4302311"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0640', 'Proteção Radiológica I', 'med', 4, 0, '{"4300438"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), '4300439', 'Laboratório de Dosimetria das Radiações', 'med', 4, 0, '{"4300437"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0641', 'Medicina Nuclear', 'med', 4, 0, '{"4300437"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0642', 'Radioterapia', 'med', 4, 0, '{"4300437"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0643', 'Física do Diagnóstico por Imagens II', 'med', 4, 0, '{"4302303", "MDR0636", "MDR0639"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0644', 'Introdução ao Ambiente Hospitalar', 'med', 2, 0, '{}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0645', 'Introdução à Saúde Ocupacional, Medicina Legal e Ética da Física Médica', 'med', 4, 0, '{"MDR0635", "MDR0637"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0646', 'Tópicos Avançados de Matemática e Física em Medicina', 'med', 4, 0, '{"MAT0216", "MDR0634"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0647', 'Estágio Hospitalar Geral', 'med', 0, 4, '{"MDR0644"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0660', 'Prática Profissional em Imagens Médicas', 'med', 0, 5, '{"MDR0647"}', '{"fisica_medica": "obrigatoria"}', null, false),
(gen_random_uuid(), 'MDR0661', 'Prática Profissional em Radioterapia', 'med', 0, 5, '{"MDR0647"}', '{"fisica_medica": "obrigatoria"}', null, false)
ON CONFLICT (course_code) DO UPDATE SET
    axis = CASE WHEN learning_trails.axis = EXCLUDED.axis THEN learning_trails.axis ELSE 'comum' END,
    course_map = learning_trails.course_map || EXCLUDED.course_map,
    title = EXCLUDED.title,
    credits_aula = EXCLUDED.credits_aula,
    credits_trabalho = EXCLUDED.credits_trabalho,
    prerequisites = EXCLUDED.prerequisites;
