INSERT INTO public.learning_trails (
    id, course_code, title, axis, 
    credits_aula, credits_trabalho, prerequisites, 
    course_map, excitation_level, requires_pcc_validation
) VALUES 
(gen_random_uuid(), '4300207', 'Integração de Conceitos Básicos de Matemática e Física', 'med', 2, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4300503', 'Perspectivas sobre diversidade em Física Médica: participação de mulheres e outros grupos sub-representados', 'med', 2, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), 'BMB0255', 'Fisiologia I', 'med', 4, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), 'HSP0141', 'Introdução à Saúde Pública', 'med', 2, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), 'BMB0269', 'Biofísica de Membranas Básica', 'med', 6, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), 'MSP4015', 'Telemedicina na Prática Médica e Segurança Digital', 'med', 1, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), 'MSP4053', 'Inovação e empreendedorismo na medicina', 'med', 1, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), 'QBQ1151', 'Introdução à Bioquímica', 'med', 2, 1, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4300441', 'Detectores de Radiação', 'med', 4, 1, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), 'QBQ0313', 'Bioquímica', 'med', 4, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4300228', 'Tratamento Estatístico de dados em Física Experimental', 'med', 4, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4302307', 'Física Matemática II', 'med', 4, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), 'MAP0214', 'Cálculo Numérico com Aplicações em Física', 'med', 4, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), 'MAT0216', 'Cálculo Diferencial e Integral III / IV', 'med', 4, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4302306', 'Mecânica II', 'med', 4, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4302308', 'Termodinâmica', 'med', 4, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4305512', 'Aprendizado de máquina e inteligência artificial em física', 'med', 4, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), 'QFL0606', 'Fundamentos de Química para Física', 'med', 6, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4300315', 'Introdução à Física Atômica e Molecular', 'med', 4, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4300408', 'Introdução à Física Nuclear', 'med', 4, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4302313', 'Física Experimental V', 'med', 4, 2, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4302314', 'Física Experimental VI', 'med', 4, 2, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4302404', 'Mecânica Quântica II', 'med', 4, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), 'MSP4085', 'Princípios básicos de inteligência artificial e saúde', 'med', 1, 0, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4300464', 'Trabalho de Conclusão de Curso', 'med', 0, 2, '{}', '{"fisica_medica": "livre"}', null, false),
(gen_random_uuid(), '4302304', 'Eletromagnetismo II', 'med', 4, 0, '{}', '{"fisica_medica": "livre"}', null, false)
ON CONFLICT (course_code) DO UPDATE SET
    course_map = learning_trails.course_map || EXCLUDED.course_map,
    title = EXCLUDED.title,
    credits_aula = EXCLUDED.credits_aula,
    credits_trabalho = EXCLUDED.credits_trabalho;
